// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// 加载 .env.local（Next.js 项目的环境变量文件）
config({ path: ".env.local" });
config(); // fallback to .env

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 使用直连端口 5432 而不是 pooler 的 6543，避免 prepared statement 冲突
    url: process.env.DATABASE_URL || "postgresql://postgres.xefagfeyqvxjgtavmmam:Aa6253763%40.@aws-1-us-east-1.pooler.supabase.com:5432/postgres",
  },
});
